### ISSUE TITLE
Are ObservationRangeBeacon measures used on localization?

### ISSUE THREAD

**Issue by corot** [mrpt-ros-pkg/mrpt_navigation#43]
Hi all, I'm trying to incorporate mrpt_msgs/ObservationRangeBeacon measures in mrpt_localization. Filter clearly gets updated (I don't use laser input anymore and still particles dance) but seems to ignore the range beacon measures:

![2016-11-08_165101](https://cloud.githubusercontent.com/assets/322610/20106029/188ee48a-a5d4-11e6-8291-f6a5e98909e7.gif)

The white arrow represents the robot pose relative to the beacon. I move 20 cm every 5 seconds but nothing changes in the filter. Moreover, particles get more and more disperse with time:

![image](https://cloud.githubusercontent.com/assets/322610/20106165/820ec92a-a5d4-11e6-8756-bd38895cbac0.png)

Is there any problem with this feature? Or do I need to change something in the configuration? The mrpt.ini file seems fine to me:

```
[MetricMap]
# Creation of maps:
occupancyGrid_count=1
gasGrid_count=0
landmarksMap_count=0
pointsMap_count=0
beaconMap_count=0

# Selection of map for likelihood: (fuseAll=-1,occGrid=0, points=1,landmarks=2,gasGrid=3)
likelihoodMapSelection=-1

# Enables (1) / Disables (0) insertion into specific maps:
enableInsertion_pointsMap=1
enableInsertion_landmarksMap=1
enableInsertion_gridMaps=1
enableInsertion_gasGridMaps=1
enableInsertion_beaconMap=1
```

My range beacon messages looks like this:

```
header: 
  seq: 23673
  stamp: 
    secs: 12081
    nsecs: 400000000
  frame_id: Seg_54W1_1
sensor_pose_on_robot: 
  position: 
    x: 0.0
    y: 0.0
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
min_sensor_distance: 0.2
max_sensor_distance: 1.0
sensor_std_range: 0.015
sensed_data: 
  - 
    range: 0.586409630196
    id: -1
```

where Seg_54W1_1 is the frame of the beacon.

Btw, if this works, I'll also implement a callback for ObservationRangeBearing. I suppose there's no reason to use ranges but not range + bearing, right?
